MODEL_SCORING_FUNCTION: "rmse"
MODEL_OUTLIER_RATIO_UPPER: 3
MODEL_OUTLIER_RATIO_LOWER: 0.33
RANDOM_STATE: 42
DATA_SPLIT_TEST_SIZE: 0.25
DATA_OHE_COLS: ["transmission", "fuelType", "brand"]
DATA_LOG_COLS: ["price", "mileage"]
DATA_LOWEST_YEAR: 2005
DATA_AUDI_MAX_PRICE: 75000
DATA_VW_MAX_PRICE: 60000
DATA_BMW_MAX_PRICE: 80000
DATA_MIN_MILEAGE: 1
DATA_MAX_MILEAGE: 150000
DATA_MIN_MPG: 18
DATA_MAX_MPG: 200
DATA_MIN_ENGINE_SIZE: 1.0
DATA_MAX_ENGINE_SIZE: 5.2
DATA_FUEL_TYPE_REMOVE: ["Other", "Electric"]
POSTCODES: {
  13: "E34JN",  # East London
  14: "B24QA",  # Birmingham 
  15: "NR13JU",  # Norwich
  16: "SO140YG",  # Southampton
  17: "BS11JQ",  # Bristol
  18: "S14PF",  # Sheffield
  19: "LS28BH",  # Leeds
  20: "L34AD",  # Bristol
  21: "NE77DN",  # Newcastle
  22: "EH12NG",  # Edinburgh
  23: "HU67RX",  # Hull
  24: "EX11SG",  # Exeter
  25: "CB13EW",  # Cambridge
  26: "CT12EH",  # Canterbury
  27: "SA11NU",  # Swansea
  28: "BT12HB",  # Belfast
}