MODEL_SCORING_FUNCTION: "rmse"
MODEL_OUTLIER_RATIO_UPPER: 3
MODEL_OUTLIER_RATIO_LOWER: 0.33
RANDOM_STATE: 42
DATA_SPLIT_TEST_SIZE: 0.25
DATA_OHE_COLS: ["transmission", "fuelType", "brand"]
DATA_LOG_COLS: ["price", "mileage"]
DATA_LOWEST_YEAR: 2005
DATA_AUDI_MAX_PRICE: 75000
DATA_VW_MAX_PRICE: 60000
DATA_BMW_MAX_PRICE: 80000
DATA_MIN_MILEAGE: 1
DATA_MAX_MILEAGE: 150000
DATA_MIN_MPG: 18
DATA_MAX_MPG: 200
DATA_MIN_ENGINE_SIZE: 1.0
DATA_MAX_ENGINE_SIZE: 5.2
DATA_FUEL_TYPE_REMOVE: ["Other", "Electric"]