name: retrain model

on:
#   push:
#     paths:
#       - 'data/Test scraped data/**.csv'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_GH_actions.txt
          
      - name: generate clean data # run train.py
        run: |
          python model/generate_clean_data.py

      - name: test clean data # run train.py
        run: |
          py.test model/test_clean_data.py

      - name: execute py script # run train.py
        run: |
          python model/train.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate data & train new model"
          git push
